### ISSUE TITLE
Include tint() color function in documentation

### ISSUE THREAD

**Issue by aghreed** [less/less-docs#229]
I don't believe I'm missing anything here, but tint() is definitely a function in LESS despite it not existing in documentation. See: https://github.com/less/less.js/issues/944

**Comment by nathancooper** [comment]
Agreed for both Tint and Shade. I discovered those two functions exist via [Codepen](http://codepen.io/anon/pen/iFfcD). As the demo shows, those functions add more perceivable gradations in color, i.e., slower to reach pure white or black.

**Comment by seven-phases-max** [comment]
>As the demo shows, those functions add more perceivable gradations in color,

Well, `tint` and `shade` are yet again just shorthands for `mix(*, white, *)` and `mix(*, black, *)` respectively so no useful functionality is really concealed in a strict sense (it's more about syntactic sugar and understanding the arithmetic behind these stuff).

**Comment by nathancooper** [comment]
Thanks, I didn't notice the reference to mix in your first comment.

On a sort of related note, is it possible for LESS to use HSB instead of HSL color space? The reason I ask is that Adobe products (perhaps other design software as well) use HSB not HSL.

It seems minor, but if you select a color in Illustrator, e.g., *#fbb03b* and make is 20% darker lowering the B(rightness) value, the resulting color isn't the same as if you used the LESS *darken(#fbb03b, 20%)* function. Sometimes the difference is subtle, but often it's not. Perhaps shade(#ffb03b, 20%) produces the desired effect?

**Comment by seven-phases-max** [comment]
>On a sort of related note, is it possible for LESS to use HSB instead of HSL color space?

See https://github.com/less/less.js/pull/1853.
