### ISSUE TITLE
Section Title Guidelines (Inconsistent casing for titles).

### ISSUE THREAD

**Issue by TravisTheTechie** [less/less-docs#346]
<img width="246" alt="screen shot 2015-07-06 at 8 04 49 am" src="https://cloud.githubusercontent.com/assets/186225/8521820/bc3b1bd2-23b5-11e5-9b1a-6a6d8b48db9e.png">

Getting Started = title case
Client-side usage = sentence case

See http://lesscss.org/

**Comment by TravisTheTechie** [comment]
Also, "With" is rarely capitalized for either casing option.

**Comment by seven-phases-max** [comment]
Thanks. Though there're too many "capital-letters inconsistent titles" in other pages to actually bother with just these two (yet?).

**Comment by TravisTheTechie** [comment]
"Title Case" is considered more formal, and "Sentence case" is the more familiar format to use. "Proper" written US English says Title Case, if you check one of the guides, but the less formal use has also been popular for some time. Consistency is the real win. A quick browse through some documentation doesn't show anything strongly formal, so either could work. If you adopt some guidelines, I can likely carve out an hour or two and help apply them. Better docs are better for everyone :book:

**Comment by seven-phases-max** [comment]
Well, personally I'd vote for:

**In Titles: Do Capitalize**
- Nouns (man, bus, book)
- Adjectives (angry, lovely, small)
- Verbs (run, eat, sleep)
- Adverbs (slowly, quickly, quietly)
- Pronouns (he, she, it)
- Subordinating conjunctions (as, because, that)

**In Titles: Do Not Capitalize**
- Articles: a, an, the
- Coordinating Conjunctions: and, but, or, for, nor, etc.
- Prepositions (~~fewer than five letters~~): on, at, to, from, by, etc.

---
(I'd only exclude the "fewer than five letters prepositions -> up" rule since `by` vs. `Among` or `in Between` look totally artificial, imho).

**Comment by lukeapage** [comment]
Anything consistent is fine by me.. I probably made plenty of the mistakes, it's just that my grammar consistency is terrible.. sorry!

**Comment by lukeapage** [comment]
thanks, just pushed to live site.
