### ISSUE TITLE
% function documentation is missing explanation for placeholder types

### ISSUE THREAD

**Issue by SetTrend** [less/less-docs#358]
The % function has a number of placeholder types (s,S,d,D,a, or A). None of these types is getting explained in the doc.

What are their meanings? What are their differences? Why are there six of them?

**Comment by seven-phases-max** [comment]
It's there:
>Placeholders:
`d, D, a, A`- can be replaced by any kind of argument (color, number, escaped value, expression, ...). If you use them in combination with string, the whole string will be used - including its quotes. However, the quotes are placed into the string as they are, they are not escaped by "/" nor anything similar.
`s, S` - can be replaced by any expression. If you use it with string, only the string value is used - quotes are omitted.

Thus it's really just *two* placeholders.

**Comment by SetTrend** [comment]
OK, I see. So what's the reason for having six instead of just two arguments here? This is very confusing.

**Comment by seven-phases-max** [comment]
lowercase + Uppercase is just because it's case-insensitive. So remaining `a` and `d` mean "argument" (I guess) and "something (usually number?) I get to use in other languages with similar function" (guesswork too). I'm pretty sure nobody remember this (you need search for issues/PR when this function were added and find out for sure :). This is usual chaos of open-source development (could be much worse).

**Comment by SomMeri** [comment]
I am closing this since the issue was clarified and placeholders are explained in docs.
