### ISSUE TITLE
@first-child pseudo class not working with extend

### ISSUE THREAD

**Issue by moshemo** [less/less-docs#395]
I am using the following code:

    header {
        &:extend(.menu all);
    }

In the less file I have the following structure:

    .menu {// CODE}
    .menu:after {// CODE}
    .menu:first-child {// CODE}
    .menu:last-child {// CODE}

In the output file, the css for .menu and .menu:after show up.  But NOT the code for .menu:first-child or .menu:last-child.

If, however, I change .menu:first-child or .menu:last-child to .menu:first and .menu:last then the css code will show up.

It seems that the hyphen is the problem.  

Any idea how to fix this?

Thanks.

**Comment by seven-phases-max** [comment]
Please note this repository is for the Less site/documentation. For the Less language/compiler issues/bug-reports use https://github.com/less/less.js.

---
Either way I can't confirm your result: [demo](http://less2css.org/#%7B%22less%22%3A%22%5Cnheader%20%7B%5Cn%20%20%20%20%26%3Aextend(.menu%20all)%3B%5Cn%7D%5Cn%5Cn.menu%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%2F*%20menu%20*%2F%7D%5Cn.menu%3Aafter%20%20%20%20%20%20%20%7B%2F*%20menu%3Aafter%20*%2F%7D%5Cn.menu%3Afirst-child%20%7B%2F*%20menu%3Afirst-child%20*%2F%7D%5Cn.menu%3Alast-child%20%20%7B%2F*%20menu%3Alast-child%20*%2F%7D%22%7D). 
(I'm closing this ticket because it's in the wrong repo anyway, but feel free to create a new one at the corresponding issue tracker, if you have an example that does not work as expected with recent Less versions).

**Comment by seven-phases-max** [comment]
Closing as "wrong repo".

**Comment by moshemo** [comment]
Sorry about that.  I reposted it on the right repo.
