### ISSUE TITLE
[Question] Display more error per file

### ISSUE THREAD

**Issue by mega-n3ss** [less/less-docs#417]
Hello,

I use `lessc --lint <files>` to detect some errors. But the lint only one error per file. Is it possible to display more errors per file ? How Can I do ? Keep me in touch please :)

Regards

**Comment by seven-phases-max** [comment]
It's currently impossible. And most likely will never be possible. The problem is that a multiple error detection requires some sort of "recovery from the current parser/evaluator error" thing (just to be able interprete the further code properly) which in its turn would be quite burdening stuff (in both amount of new code / performance sense) for the compiler (thus it's barely ever to be considered to be worth relatively rare use-case).

**Comment by seven-phases-max** [comment]
Closing as "no such feature".
