### ISSUE TITLE
Questionable Less / LESS description.

### ISSUE THREAD

**Issue by seven-phases-max** [less/less-docs#443]
I occasionally steeped into https://github.com/less/less-docs#capitalizing-less:
>When referring to Less, know your context. LESS (Leaner Style Sheets) is the stylesheet language based on CSS. Less or Less.js is the library / compiling tool.

*Nooooooo!* This does not look any close to what we actually agreed at #64 (and #78, see the poll count below). My vision/usage of this thing is totally different: 
 - Language, library and compiler have the same name: `Less` ("Less", "Less Language", "Less Library", "Less Compiler" etc.).
 - `Less.js`/`less.js` may be used when it's necessary to stress the particular implementation, repository, script, whatever in an ambiguous contexts.
 - `LESS` may never* be used anywhere at all (in a new content of course)!
  _ * <sub>It may only appear as the result of an auto/allchars-capitalization, e.g. as in "LESS LANGUAGE AND ITS USAGE".</sub>

---
Sure, it's true it was `LESS` and/as-in (rumored) "Leaner Style Sheets" initially, but it's not anymore (since [Feb 5, 2014](https://github.com/less/less-docs/pull/103)). Using both titles makes no sense at all and only is confusing/misleading.

---
**Poll count** per #64/#78:
### Less - 5
 - matthew-dean (mostly)
 - lukeapage
 - jonschlinkert ([post-factum](https://github.com/less/less-docs/pull/78#issuecomment-32020675))
 - Synchro
 - SomMeri
### LESS - 1
 - cloudhead (rumored)
### Abstained - 1
 - seven-phases-max

**Comment by matthew-dean** [comment]
Yeah, except 
a. I was wrong that it wasn't an acronym, as you pointed out, 
b. more importantly, it terribly obscures grammar, and not just for titles, which you demonstrate;  that is, I found myself rewriting sentences because of the ambiguous-sounding nature of "Less",
c. the distinction between "Less" and "Less.js" seems too slight, and
d. anecdotally, most people online tend to capitalize as LESS because it's semantically similar to CSS - which is kind of a circular proof, I know, if it was historically written as "LESS" in the old docs.

But, what I found is that writing documentation for Less.js started to change my perspective drastically on the code underneath it. Things make sense up until the point where you have to actually explain it to someone else, and then the parts that don't make sense tend to become obvious.

I don't think we need to tell anyone how to capitalize at all, and that can be removed.

But of all the things to stick a flag in as far as important work related to Less, this isn't one of them. If you feel strongly about it, feel free to change it. In the end, people will capitalize it in a way that makes sense to them. What's more important is communicating features clearly.

**Comment by seven-phases-max** [comment]
>If you feel strongly about it, feel free to change it. 

OK, then I'm going to replace the whole section with just "The official name of the language is Less".

**Comment by matthew-dean** [comment]
> So, in addition to above I'm also about to indirectly push a "Minimize usage of Less.js" suggestion.

How do you mean? You mean more emphasis / advertising of using third-party tools?

**Comment by seven-phases-max** [comment]
>How do you mean? You mean more emphasis / advertising of using third-party tools?

Ah, sorry bad lang., no, I mean just using "Less" (almost) everywhere in th docs instead of "Less.js" (with a few few exception). But it's not like search and replace right now but in careful steps. With a general rule into readme like:
"When in doubt if it should be `Less` or `Less.js` - save you time and use `Less` (if it goes really wrong you'll be corrected)"

**Comment by seven-phases-max** [comment]
OK, so... by looking closer at the docs with above considerations in mind, I can see this "Less/Less.js" inconsistency across the docs (either version) is itself a major problem. So I decide make a more formal proposal of the simplest guideline [here](https://github.com/less/less-meta/issues/24) (derived from how I personally use these names for a while by now).

**Comment by seven-phases-max** [comment]
Closed in favour of https://github.com/less/less-meta/issues/24.
