### ISSUE TITLE
What does --no-js mean?

### ISSUE THREAD

**Issue by netAction** [less/less-docs#445]
Found here:

https://github.com/less/less-docs/blob/master/content/usage/command-line-usage.md#disable-javascript

How can Javascript be included if this flag is not activated?

**Comment by seven-phases-max** [comment]
It means exactly just that: "Disable inline JavaScript".

>How can Javascript be included if this flag is not activated?

No way. The flag is meant to prohibit this.

**Comment by seven-phases-max** [comment]
Closing as not an issue.

**Comment by netAction** [comment]
Thanks. Please be aware of the *not*. I would like to know how Javascript can be executed or imported or whatever if the flag is *not* set.

This is an issue as the information is missing in the referenced docs.

**Comment by seven-phases-max** [comment]
Yes, sorry - I initially misread your question. Inline javascript may be emmited via backticks. [For example](http://less2css.org/#%7B%22less%22%3A%22%5Cnfoo%20%7B%5Cn%5Ct%40x%3A%20%60Math.random()%60%3B%5Cn%20%20%20%20a%3A%20%40x%3B%5Cn%20%20%20%20b%3A%20%40x%3B%5Cn%7D%5Cn%22%7D).

>This is an issue as the information is missing in the referenced docs.

Yes, #415. (Technically it's not quite decided if it's really deprecated or not, but yes - "Nearly Deprecated" - hence no bothering to document that. Any JavaScript code should go into a plugin, since plugins have become extremely easy - see https://github.com/less/less.js/pull/2479. The detailed plugin documentation is WIP in the next version of the docs since currently there're two plugin formats to be unified in v3).

**Comment by matthew-dean** [comment]
@netAction Note also that inline JavaScript is disabled by default in Less 3.0 because of security concerns (and the much safer plugin method). Inline JS is essentially an `eval()` in your `.less` file, which can cause security problems if, for example, some of your variable values are set by users. (Whereas `@plugin` is subject to CORS restrictions.)

So, in Less 3.0 the option will be `--js` for `lessc` or `javascriptEnabled: true` for the Less JS API if you want to enable this option. However, using plugins is still recommended over that approach.

**Comment by matthew-dean** [comment]
Closing in favor of #415. This should be mentioned when documenting deprecation.
