### ISSUE TITLE
how to import mutiple less files?

### ISSUE THREAD

**Issue by JanWing1995** [less/less-docs#470]
introduction： 
    vue: 2.5.2
    less: 3.0.1
    less-loader: 4.1.0
    my project‘s tables of contents is following:
```
  styles
            ---common
                                ---header.less
                                ---slider.less
                                ---index.less(import header.less&&slider.less)
            ---components
                                ---header.less
                                ---slider.less
                                ---index.less(import header.less&&slider.less)
           ---theme.less
           ---mixins.less
           ---index.less(import theme&&mixins&&common/index&&componens/index)
```
and then ,there is apearing error:
    less files at comon/components  can't resolve functions  at mixins.less

**Comment by seven-phases-max** [comment]
Note this is the repository for the Less documentation. For Less issues/bug reports please use https://github.com/less/less.js/issues. 
Although you question is more about using `less` with`vue` and/or `less-loader` rather than about `less` as such.

Also note that in general issue trackers at GiHub are not support forums or Q/A portals. They are meant mostly *only* for bug reports and features requests. For generic "How Do I" questions please use more appropriate resources. Like [SO](https://stackoverflow.com/questions/tagged/vue.js+less) for example.

**Comment by seven-phases-max** [comment]
Closing as "wrong repo" (and not an issue anyway).
